openapi: '3.0.0'
info:
  title: 'Bored API'
  version: '1.0.0'
  description: "Bored Api: Find an activity for you if you are bored"
  license: 
    name: Moneris  
  servers:
      - url: 'https://gnrdev01-29.moneris.com/cardprogram-api'

paths:
    
  /activity:    
    get:
      summary: Find an activity if you are feeling bored
      responses:
        '200':
          description: get a brand new activity to do when you are bored          
          content: 
            application/json:
              examples:
                result:
                  value:
                   {
                       "activityId":0,
                       "name": "play a video game"
                   }            
        500:
          description: Unexpected error


  /activity/{activityId}:
    get:
    summary: Find an activity by a given activityId if you are feeling bored
      responses:
        '200':
          description: get a brand new activity to do when you are bored          
        400:
          description: No activity found for a given activityId
        500:
          description: Unexpected error
      
  /health:
    get:
        summary: Get health check
        responses:
         '200':
            description: get a brand new activity to do when you are bored          
          404:
            description: no activity found           
          500:
            description: Unexpected error


