openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Bored API'
  description: Bored API
  /Find an activity for you if you are bored

paths:
  /activity:    
    get:
      summary: Find an activity if you are feeling bored
      responses:
        '200':
          description: get a brand new activity to do when you are bored          
        404:
          description: no activity found           
        500:
          description: Unexpected error
    
  /health:
    get:
        summary: Get health check
        responses:
         '200':
            description: get a brand new activity to do when you are bored          
          404:
            description: no activity found           
          500:
            description: Unexpected error


